name:                ha
version:             0.1.0.0
github:              "syouzan420/HA"
license:             BSD3
author:              "yokoP"
maintainer:          "syouzanponkikki@yahoo.co.jp"
copyright:           "2019 yokoP"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/syouzan420/HA#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ha-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gloss
    - gloss-juicy
    - ha

tests:
  ha-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ha
